const colors = {
  light: {
    text: '#ffffff',
    tint: '#9b30ff',
    background: '#0a0a12',
    foreground: '#ffffff',
    card: '#0f0f1a',
    cardForeground: '#ffffff',
    primary: '#9b30ff',
    primaryForeground: '#ffffff',
    secondary: '#ff00c8',
    secondaryForeground: '#ffffff',
    muted: '#1a1a2e',
    mutedForeground: '#8b8bb5',
    accent: '#ff00c8',
    accentForeground: '#ffffff',
    destructive: '#ff4444',
    destructiveForeground: '#ffffff',
    border: '#2d2d4a',
    input: '#2d2d4a',
  },
  dark: {
    text: '#ffffff',
    tint: '#9b30ff',
    background: '#0a0a12',
    foreground: '#ffffff',
    card: '#0f0f1a',
    cardForeground: '#ffffff',
    primary: '#9b30ff',
    primaryForeground: '#ffffff',
    secondary: '#ff00c8',
    secondaryForeground: '#ffffff',
    muted: '#1a1a2e',
    mutedForeground: '#8b8bb5',
    accent: '#ff00c8',
    accentForeground: '#ffffff',
    destructive: '#ff4444',
    destructiveForeground: '#ffffff',
    border: '#2d2d4a',
    input: '#2d2d4a',
  },
  radius: 4,
};

export default colors;
